#!/bin/bash

PTYHON_VERSION=$DOCKER_TAG

if [ $DOCKER_TAG == "latest" ]
then
  docker build . --build-arg PTYHON_VERSION="3.8.2" -t ${IMAGE_NAME}
else
  docker build . --build-arg PTYHON_VERSION=${PTYHON_VERSION} -t ${IMAGE_NAME}
fi